#!/bin/bash

_get_zlink () {
    if [[ $GIT_REPO ]]
    then
        echo "https://github.com/${GIT_REPO}/archive/master.zip"
    else
        echo "https://github.com/badmunda011/new/archive/master.zip" 
    fi
}

_run_python_code() {
    python3${pVer%.*} -c "$1"
}

_run_legendpackgit() {
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO = "https://github.com/badmunda011/new"
ACTIVE_BRANCH_NAME = "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_run_legendgit() {
    local repolink=$(_get_repolink)
    $(_run_python_code 'from git import Repo
import sys
OFFICIAL_UPSTREAM_REPO="'$repolink'"
ACTIVE_BRANCH_NAME = "'$UPSTREAM_REPO_BRANCH'" or "master"
repo = Repo.init()
origin = repo.create_remote("temponame", OFFICIAL_UPSTREAM_REPO)
origin.fetch()
repo.create_head(ACTIVE_BRANCH_NAME, origin.refs[ACTIVE_BRANCH_NAME])
repo.heads[ACTIVE_BRANCH_NAME].checkout(True) ')
}

_start_bot () {
    local zippath
    zippath="LEGENDBOT.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_zlink) -O "$zippath"
    echo "  Unpacking Data ..."
    LEGENDPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    _run_legendpackgit
    cd $LEGENDPATH
    _run_legendgit
    python3 ../setup/updater.py ../requirements.txt requirements.txt
    chmod -R 755 bin
    echo "    UserBot    "
    python3 -m Legendbot
}

_start_bot
